### ISSUE TITLE
Experience with ART Cameras

### ISSUE THREAD

**Issue by sroettgermann** [DWilches/Vrpn2Unity#1]
Hello Daniel. Today I found your project and tried to use it with my ART Tracking System (DTrack). I was wondering if you have any experience regarding that. I'm not sure how to read the data from the network properly right now. 
Maybe you have a hint. Thanks in advance.

Sebastian

**Comment by dwilches** [comment]
Hi Sebastian,

As this library only works with Vrpn, your options are:
* Can you configure ART to use Vrpn instead of Dtrack? Other tracking systems allow switching between them. If yes, then you can use `Vrpn2Unity` out-of-the-box.
* Vrpn has a virtual device for Dtrack. So you can configure Vrpn to read from ART, and expose the data as if it were native Vrpn. Search for this in Vrpn's docs: `vrpn_Tracker_DTrack` (I have never configured it though, I've just seen it around.)
* You can write your own library like `Vrpn2Unity`but for DTrack. You will need to use DTrack's API for this. I guess they have a low-level API (C or C++) you can use.

Let me know if this helps.

**Comment by sroettgermann** [comment]
Hi Daniel,

thank you very much for your kind answer. 

Yesterday I did a few tests with our tracking system and your package. Here are my results:

- I configured the ARTrackController in such a way, that it sends the tracking data via VRPN.
- then I took your MouseBehaviour example and changed everything according to the DTrack/ART data. That was a bit tricky due to the fact that the naming is a bit confusing. ART is the brand, respectively the manufacturer and DTrack is on the one hand the software you use to read the data from the network AND the name of their SDK. 
- but now it is working. I'm able to start the vrpn_server on the pc and get the data from the network. Then configure my own DTrackBehaviour Class to get the position and orientation data from the vrpn-data the ARTrackController sends and forward them to my GameObject in Unity

But there is one thing left, that I'm wondering about:
- Like I described above it is working when I'm running the configured vrpn_server.exe on my pc and when I'm setting the devicename to "DTrack@localhost"
- when I'm setting devicename to "DTrack@IP_OF_MY_ARTRACKCONTROLLER" it isn't working anymore. That is a bit confusing to me. Maybe you have more experience with VRPN and know this behaviour.

Thank you very much.

Just one more thing regarding your hint about the own library:
- I wanted to avoid this, because I'm and egineer and not a programmer. ; ) Yes, they have a low-level API (in C++), but using VRPN it is way easier for me. ; )
